#!/usr/bin/env python
import json
import glob

for file in glob.glob('log.*'):
    with open(file, mode='r') as fp:
        x = 0
        for line in fp:
            entry = json.loads(line.rstrip())
            if "_" in entry["ts"]:
                assert entry["ts"]["_"] == x + 1
                x += 1
