#!/usr/bin/env python
import json
import glob


def compare(v1, v2):
    lt = False
    gt = False
    for key in set(v1) | set(v2):
        a = v1.get(key, 0)
        b = v2.get(key, 0)
        lt |= a < b
        gt |= a > b
        if lt and gt:
            break
    return gt - lt


def merge(v1, v2):
    v3 = v1.copy()
    for key, value in v2.items():
        v3[key] = max(value, v1.get(key, 0))
    return v3


for file in glob.glob('log.*'):
    with open(file, mode='r') as fp:
        log = [json.loads(line.rstrip()) for line in fp]
        seen = set()
        ts = {}
        for entry in log:
            # ts >= u.prev
            assert compare(ts, entry["prev"]) > -1
            # not executed twice
            assert entry["id"] not in seen

            ts = merge(ts, entry["ts"])
            seen.add(entry["id"])
