#!/bin/bash

ids=$(pyro4-nsc list | grep '^replica:' | cut -d ' ' -f1 | cut -d ':' -f2)

# do some writes first
for id in $ids; do
    python tools/bombard.py $id &
done

for _ in $(seq 1 10); do
    python tools/bombard2.py &
done

# wait for jobs to complete
wait

# wait for replica sync
sleep 10

for id in $ids; do
    python tools/get_log.py $id > "log.$id"
done

head=$(echo "$ids" | head -n 1)
tail=$(echo "$ids" | tail -n +2)

for id in $tail; do
    if [ $(diff "log.$head" "log.$id") ]; then
        echo "Found mismatched logs:"
        echo $head
        echo $id
        exit
    fi
done
